# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2016, 1, 7, 16, 33, 42, 283012, tzinfo=utc)),
        ),
    ]
