# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20160108_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2016, 1, 8, 16, 37, 17, 34768, tzinfo=utc)),
        ),
    ]
